# server:
#   service:
#     type: ClusterIP

#   ingress:
#     enabled: true
#     ingressClassName: alb

#     annotations:
#       alb.ingress.kubernetes.io/scheme: internet-facing
#       alb.ingress.kubernetes.io/target-type: ip
#       alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
#       alb.ingress.kubernetes.io/group.name: shared-alb

#     hosts:
#       - "*"

#     paths:
#       - /
#     pathType: Prefix

# configs:
#   params:
#     server.insecure: true